---
# tasks file for conan-exiles-ansible-role
- name: Upgrade system
  become: "True"
  apt:
    upgrade: dist
    update_cache: "True"
    autoremove: "True"
    install_recommends: "True"

- name: Create game installation folder
  become: "True"
  become_user: "{{ steamcmd_user }}"
  file:
    path: "{{ game_installation_folder }}"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: u=rwx,g=r,o=r
    state: directory

- name: Prepare server installation script
  become: "True"
  become_user: "{{ steamcmd_user }}"
  template:
    src: install_conan_server.txt
    dest: "{{ game_installation_script }}"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: u=rwx,g=r,o=r

- name: Install Conan Exiles Server
  become: "True"
  become_user: "{{ steamcmd_user }}"
  command: "{{ steamcmd_command }} +runscript {{ game_installation_script }}"
  ignore_errors: "True"
  args:
    chdir: "{{ steamcmd_installation_folder }}"
    creates: "{{ game_installation_folder }}/ConanSandboxServer.exe"

- name: Pack install folder
  become: "True"
  become_user: "{{ steamcmd_user }}"
  community.general.archive:
    path: "{{ game_installation_folder }}"
    dest: "{{ game_installation_folder }}_pack.tar.bz2"
    format: bz2
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: u=rwx,g=rwx,o=rwx
  when: conan_debug == 'True'

- name: Copy packed files
  become: "True"
  become_user: "{{ steamcmd_user }}"
  fetch:
    src: "{{ game_installation_folder }}_pack.tar.bz2"
    dest: tmp/files
  when: conan_debug == 'True'
